[package]
name = "pb"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
convex_sync_types = { path = "../convex/sync_types" }
errors = { path = "../errors" }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
value = { path = "../value" }

[dev-dependencies]
convex_sync_types = { path = "../convex/sync_types", features = ["testing"] }
errors = { path = "../errors", features = ["testing"] }
proptest = { workspace = true }
value = { path = "../value", features = ["testing"] }

[build-dependencies]
pb_build = { path = "../pb_build" }

[package.metadata.cargo-machete]
ignored = [
    # Prost/Tonic required via tonic macro
    "prost",
    "prost_types",
    "tonic",
]
