[package]
name = "isolate"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

build = "build.rs"
include = ["data"]

[lib]
doctest = false

[package.metadata.cargo-udeps.ignore]
normal = ["mysql"]
development = ["mysql"]

[dependencies]
anyhow = { workspace = true }
async-broadcast = { workspace = true }
async-channel = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
async_lru = { path = "../async_lru" }
axum = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
cmd_util = { path = "../cmd_util" }
common = { path = "../common" }
const-oid = { workspace = true }
convex_macro = { path = "../convex_macro" }
crossbeam-channel = { workspace = true }
database = { path = "../database" }
deno_core = { workspace = true }
deno_core_icudata = { workspace = true }
derive_more = { workspace = true }
elliptic-curve = { workspace = true }
encoding_rs = { workspace = true }
errors = { path = "../errors" }
file_storage = { path = "../file_storage" }
futures = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
humansize = { workspace = true }
imbl = { workspace = true }
indexing = { path = "../indexing" }
itertools = { workspace = true }
keybroker = { path = "../keybroker" }
maplit = { workspace = true, optional = true }
metrics = { path = "../metrics" }
mime = { workspace = true }
model = { path = "../model" }
must-let = { workspace = true, optional = true }
p256 = { workspace = true }
p384 = { workspace = true }
parking_lot = { workspace = true }
pb = { path = "../pb" }
phf = { workspace = true }
prometheus = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
proptest-http = { workspace = true, optional = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
regex = { workspace = true }
request_context = { path = "../request_context" }
ring = { workspace = true }
rsa = { workspace = true }
runtime = { path = "../runtime" }
search = { path = "../search" }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
sourcemap = { workspace = true }
spki = { workspace = true }
storage = { path = "../storage", optional = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
usage_tracking = { path = "../usage_tracking" }
uuid = { workspace = true }
value = { path = "../value" }
vector = { path = "../vector" }

[build-dependencies]
anyhow = { workspace = true }
common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
async-broadcast = { workspace = true }
async-channel = { workspace = true }
common = { path = "../common", features = ["testing"] }
database = { path = "../database", features = ["testing"] }
errors = { path = "../errors", features = ["testing"] }
hex = { workspace = true }
hyper = { workspace = true }
indexing = { path = "../indexing", features = ["testing"] }
keybroker = { path = "../keybroker", features = ["testing"] }
maplit = { workspace = true }
metrics = { path = "../metrics", features = ["testing"] }
model = { path = "../model", features = ["testing"] }
must-let = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
proptest-http = { workspace = true }
request_context = { path = "../request_context", features = ["testing"] }
runtime = { path = "../runtime", features = ["testing"] }
search = { path = "../search", features = ["testing"] }
shape_inference = { path = "../shape_inference", features = ["testing"] }
storage = { path = "../storage", features = ["testing"] }
tempfile = { workspace = true }
usage_tracking = { path = "../usage_tracking", features = ["testing"] }
value = { path = "../value", features = ["testing"] }
vector = { path = "../vector", features = ["testing"] }

[features]
testing = [
    "common/testing",
    "database/testing",
    "errors/testing",
    "indexing/testing",
    "keybroker/testing",
    "maplit",
    "metrics/testing",
    "model/testing",
    "must-let",
    "proptest",
    "proptest-derive",
    "proptest-http",
    "runtime/testing",
    "search/testing",
    "storage",
    "storage/testing",
    "tempfile",
    "usage_tracking/testing",
    "value/testing",
    "vector/testing",
    "request_context/testing",
]
tracy-tracing = ["common/tracy-tracing"]

[package.metadata.cargo-machete]
ignored = [
    # Generated code depends on phf
    "phf",
]
