[package]
name = "sync"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
application = { path = "../application" }
cmd_util = { path = "../cmd_util" }
common = { path = "../common" }
database = { path = "../database" }
errors = { path = "../errors" }
futures = { workspace = true }
isolate = { path = "../isolate" }
keybroker = { path = "../keybroker" }
metrics = { path = "../metrics" }
model = { path = "../model" }
parking_lot = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
request_context = { path = "../request_context" }
serde = { workspace = true }
serde_json = { workspace = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
tracing = { workspace = true }

[dev-dependencies]
application = { path = "../application", features = ["testing"] }
common = { path = "../common", features = ["testing"] }
convex_macro = { path = "../convex_macro" }
database = { path = "../database", features = ["testing"] }
errors = { path = "../errors", features = ["testing"] }
isolate = { path = "../isolate", features = ["testing"] }
keybroker = { path = "../keybroker", features = ["testing"] }
metrics = { path = "../metrics", features = ["testing"] }
model = { path = "../model", features = ["testing"] }
must-let = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
request_context = { path = "../request_context", features = ["testing"] }
runtime = { path = "../runtime", features = ["testing"] }

[features]
testing = [
    "application/testing",
    "common/testing",
    "database/testing",
    "errors/testing",
    "isolate/testing",
    "keybroker/testing",
    "metrics/testing",
    "model/testing",
    "proptest",
    "proptest-derive",
    "request_context/testing",
]
