version: "3"

services:
  backend:
    image: ghcr.io/get-convex/self-hosted-backend:latest
    ports:
      - "${PORT:-3210}:${PORT:-3210}"
      - "${SITE_PROXY_PORT:-3211}:${SITE_PROXY_PORT:-3211}"
    volumes:
      - data:/convex/data
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}
      - INSTANCE_SECRET=${INSTANCE_SECRET}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS}
      - URL_BASE=${URL_BASE:-http://127.0.0.1}
      - CONVEX_CLOUD_ORIGIN=${URL_BASE}:${PORT}
      - CONVEX_SITE_ORIGIN=${URL_BASE}:${SITE_PROXY_PORT}
      - PORT=${PORT}
      - SITE_PROXY_PORT=${SITE_PROXY_PORT}
    container_name: convex-local-backend
    healthcheck:
      test: curl -f http://localhost:$${PORT}/version
      interval: 5s
      start_period: 5s

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    image: ghcr.io/get-convex/self-hosted-dashboard:latest
    ports:
      - "${DASHBOARD_PORT:-6790}:6790"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=http://127.0.0.1:3210
      - NEXT_PUBLIC_ADMIN_KEY=${ADMIN_KEY}
    depends_on:
      backend:
        condition: service_healthy

volumes:
  data:
